#
# File: Darkpan.msg
# Date: 13-Feb-2015
# By  : Kevin L. Esteb
#
# These are the messages for XAS Darkpan modules.
#

[messages]
chi_set      = error: %s, for %s, reason: %s
chi_get      = error: %s, for %s, reason: %s
badversion   = illegal version for %s, found '%s': %s
noarch       = unknow archive type: %s
nofiles      = no files found in archive, reason: %s
unknownarc   = unknown archive type: %s
badrequest   = a bad request was made to: %s, reasom: %s
processed    = processed: %s
invalid_meta = the meta file is invalid, reason: %s
nocreate     = unable to create %s

